sudo: required
cache: pip
matrix:
  include:
  - os: linux
    dist: bionic
    language: python
    python: "3.7"
    compiler:
      - gcc
    script: 
      - "sh build.sh && python3 build.py"
  - os: ios
    script: 
      - "sh build.sh && python3 build.py && python3 build_ios.py"