sudo: required
cache: pip
matrix:
  include:
  - os: linux
    dist: bionic
    language: python
    python: "3.7"
    compiler:
      - gcc
    script: 
      - "python3 build.py"
  - os: ios
    script: 
      - "python3 build.py"