sudo: required
matrix:
  include:
  language: python
  cache: pip
  python: "3.7"
  - os: linux
    dist: bionic
    compiler:
      - gcc
    script: 
      - "sh build.sh"
  - os: ios
    dist: bionic
    compiler:
      - gcc
    script: 
      - "sh build.sh"