sudo: required
language: python
cache: pip
python: "3.7"
matrix:
  include:
  - os: linux
    dist: bionic
    compiler:
      - gcc
    script: 
      - "sh build.sh"
  - os: ios
    script: 
      - "sh build.sh"