sudo: required
matrix:
  include:
  - os: linux
    language: python
    cache: pip
    python: "3.7"
    dist: xenial
    compiler:
      - gcc
    script: 
      - "sh build.sh"
  install:
    - conan user