# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ios:
    runs-on: macOS-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Build
          env:
            CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
            CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
          run: |
            sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
            python build_ios.py
        - name: Artifacts
          uses: actions/upload-artifact@v2
          with:	
            name: build
            path: build/**
  macos:
    runs-on: macOS-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Build
          env:
            CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
            CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
          run: |
            python build.py
        - name: Artifacts
          uses: actions/upload-artifact@v2
          with:	
            name: build
            path: build/**
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
              
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build
      env:
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
      run: |
        python build.py
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:	
        name: build
        path: build/**
